In [ ]:
import pandas as pd
import numpy as np
import keras as tf

In [ ]:
data=pd.read_csv("/content/breast_cancer.csv")
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
data['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
#deleting the data
data = data.drop(['Unnamed: 32','id'],axis=1)
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
#Check Problem for Multicolinearity
data.corr()
#radius vs perimeter_mean, area_mean, concave points_mean,radius_worst, perimeter_worst, area_worst
cols=["perimeter_mean","area_mean", "concave points_mean","radius_worst", "perimeter_worst", "area_worst"]
data= data.drop(cols,axis=1)
data.head()

<ipython-input-6-d1c8b8aaff01>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()


diagnosis  radius_mean  texture_mean  smoothness_mean  compactness_mean  \
0         M        17.99         10.38          0.11840           0.27760   
1         M        20.57         17.77          0.08474           0.07864   
2         M        19.69         21.25          0.10960           0.15990   
3         M        11.42         20.38          0.14250           0.28390   
4         M        20.29         14.34          0.10030           0.13280   

   concavity_mean  symmetry_mean  fractal_dimension_mean  radius_se  \
0          0.3001         0.2419                 0.07871     1.0950   
1          0.0869         0.1812                 0.05667     0.5435   
2          0.1974         0.2069                 0.05999     0.7456   
3          0.2414         0.2597                 0.09744     0.4956   
4          0.1980         0.1809                 0.05883     0.7572   

   texture_se  ...  concave points_se  symmetry_se  fractal_dimension_se  \
0      0.9053  ...            0.01587      0.03003              0.006193   
1      0.7339  ...            0.01340      0.01389              0.003532   
2      0.7869  ...            0.02058      0.02250              0.004571   
3      1.1560  ...            0.01867      0.05963              0.009208   
4      0.7813  ...            0.01885      0.01756              0.005115   

   texture_worst  smoothness_worst  compactness_worst  concavity_worst  \
0          17.33            0.1622             0.6656           0.7119   
1          23.41            0.1238             0.1866           0.2416   
2          25.53            0.1444             0.4245           0.4504   
3          26.50            0.2098             0.8663           0.6869   
4          16.67            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 25 columns]

In [ ]:
data.corr()
#texture_mean vs texture_worst,
#smoothness_mean vs smoothness_worst
#compactness_mean vs concavity_mean, concavity_worst, concave point_worst, compactness_worst
#concavity_mean vs compactness_mean, concavity_worst, concave points_worst

cols1=["smoothness_worst", "concavity_mean","texture_worst", "concavity_worst", "concave points_worst", "compactness_worst"]
data=data.drop(cols1,axis=1)

<ipython-input-7-4d6dd8d2eaad>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()


In [ ]:

#radius_se vs perimeter_se, area_se
#perimeter_se vs radius_se, area_se
cols2=["perimeter_se", "area_se"]
data=data.drop(cols2,axis=1)


In [ ]:
data.corr()

<ipython-input-32-c44ded798807>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()


radius_mean  texture_mean  smoothness_mean  \
radius_mean                 1.000000      0.323782         0.170581   
texture_mean                0.323782      1.000000        -0.023389   
smoothness_mean             0.170581     -0.023389         1.000000   
compactness_mean            0.506124      0.236702         0.659123   
symmetry_mean               0.147741      0.071401         0.557775   
fractal_dimension_mean     -0.311631     -0.076437         0.584792   
radius_se                   0.679090      0.275869         0.301467   
texture_se                 -0.097317      0.386358         0.068406   
smoothness_se              -0.222600      0.006614         0.332375   
compactness_se              0.206000      0.191975         0.318943   
concavity_se                0.194204      0.143293         0.248396   
concave points_se           0.376169      0.163851         0.380676   
symmetry_se                -0.104321      0.009127         0.200774   
fractal_dimension_se       -0.042641      0.054458         0.283607   
symmetry_worst              0.163953      0.105008         0.394309   
fractal_dimension_worst     0.007066      0.119205         0.499316   

                         compactness_mean  symmetry_mean  \
radius_mean                      0.506124       0.147741   
texture_mean                     0.236702       0.071401   
smoothness_mean                  0.659123       0.557775   
compactness_mean                 1.000000       0.602641   
symmetry_mean                    0.602641       1.000000   
fractal_dimension_mean           0.565369       0.479921   
radius_se                        0.497473       0.303379   
texture_se                       0.046205       0.128053   
smoothness_se                    0.135299       0.187321   
compactness_se                   0.738722       0.421659   
concavity_se                     0.570517       0.342627   
concave points_se                0.642262       0.393298   
symmetry_se                      0.229977       0.449137   
fractal_dimension_se             0.507318       0.331786   
symmetry_worst                   0.510223       0.699826   
fractal_dimension_worst          0.687382       0.438413   

                         fractal_dimension_mean  radius_se  texture_se  \
radius_mean                           -0.311631   0.679090   -0.097317   
texture_mean                          -0.076437   0.275869    0.386358   
smoothness_mean                        0.584792   0.301467    0.068406   
compactness_mean                       0.565369   0.497473    0.046205   
symmetry_mean                          0.479921   0.303379    0.128053   
fractal_dimension_mean                 1.000000   0.000111    0.164174   
radius_se                              0.000111   1.000000    0.213247   
texture_se                             0.164174   0.213247    1.000000   
smoothness_se                          0.401964   0.164514    0.397243   
compactness_se                         0.559837   0.356065    0.231700   
concavity_se                           0.446630   0.332358    0.194998   
concave points_se                      0.341198   0.513346    0.230283   
symmetry_se                            0.345007   0.240567    0.411621   
fractal_dimension_se                   0.688132   0.227754    0.279723   
symmetry_worst                         0.334019   0.094543   -0.128215   
fractal_dimension_worst                0.767297   0.049559   -0.045655   

                         smoothness_se  compactness_se  concavity_se  \
radius_mean                  -0.222600        0.206000      0.194204   
texture_mean                  0.006614        0.191975      0.143293   
smoothness_mean               0.332375        0.318943      0.248396   
compactness_mean              0.135299        0.738722      0.570517   
symmetry_mean                 0.187321        0.421659      0.342627   
fractal_dimension_mean        0.401964        0.559837      0.446630   
radius_se                     0.1

In [ ]:
#compactness_se	 vs concavity_se,fractal_dimension_se
cols=["concavity_se","fractal_dimension_se"]
data=data.drop(cols,axis=1)
data.corr()

<ipython-input-9-65e9555a51ef>:4: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()


radius_mean  texture_mean  smoothness_mean  \
radius_mean                 1.000000      0.323782         0.170581   
texture_mean                0.323782      1.000000        -0.023389   
smoothness_mean             0.170581     -0.023389         1.000000   
compactness_mean            0.506124      0.236702         0.659123   
symmetry_mean               0.147741      0.071401         0.557775   
fractal_dimension_mean     -0.311631     -0.076437         0.584792   
radius_se                   0.679090      0.275869         0.301467   
texture_se                 -0.097317      0.386358         0.068406   
smoothness_se              -0.222600      0.006614         0.332375   
compactness_se              0.206000      0.191975         0.318943   
concave points_se           0.376169      0.163851         0.380676   
symmetry_se                -0.104321      0.009127         0.200774   
symmetry_worst              0.163953      0.105008         0.394309   
fractal_dimension_worst     0.007066      0.119205         0.499316   

                         compactness_mean  symmetry_mean  \
radius_mean                      0.506124       0.147741   
texture_mean                     0.236702       0.071401   
smoothness_mean                  0.659123       0.557775   
compactness_mean                 1.000000       0.602641   
symmetry_mean                    0.602641       1.000000   
fractal_dimension_mean           0.565369       0.479921   
radius_se                        0.497473       0.303379   
texture_se                       0.046205       0.128053   
smoothness_se                    0.135299       0.187321   
compactness_se                   0.738722       0.421659   
concave points_se                0.642262       0.393298   
symmetry_se                      0.229977       0.449137   
symmetry_worst                   0.510223       0.699826   
fractal_dimension_worst          0.687382       0.438413   

                         fractal_dimension_mean  radius_se  texture_se  \
radius_mean                           -0.311631   0.679090   -0.097317   
texture_mean                          -0.076437   0.275869    0.386358   
smoothness_mean                        0.584792   0.301467    0.068406   
compactness_mean                       0.565369   0.497473    0.046205   
symmetry_mean                          0.479921   0.303379    0.128053   
fractal_dimension_mean                 1.000000   0.000111    0.164174   
radius_se                              0.000111   1.000000    0.213247   
texture_se                             0.164174   0.213247    1.000000   
smoothness_se                          0.401964   0.164514    0.397243   
compactness_se                         0.559837   0.356065    0.231700   
concave points_se                      0.341198   0.513346    0.230283   
symmetry_se                            0.345007   0.240567    0.411621   
symmetry_worst                         0.334019   0.094543   -0.128215   
fractal_dimension_worst                0.767297   0.049559   -0.045655   

                         smoothness_se  compactness_se  concave points_se  \
radius_mean                  -0.222600        0.206000           0.376169   
texture_mean                  0.006614        0.191975           0.163851   
smoothness_mean               0.332375        0.318943           0.380676   
compactness_mean              0.135299        0.738722           0.642262   
symmetry_mean                 0.187321        0.421659           0.393298   
fractal_dimension_mean        0.401964        0.559837           0.341198   
radius_se                     0.164514        0.356065           0.513346   
texture_se                    0.397243        0.231700           0.230283   
smoothness_se                 1.000000        0.336696           0.328429   
compactness_se                0.336696        1.000000           0.744083   
concave points_se             0.328429        0.744083           1.000000   
symmetry_se            

In [ ]:
data.describe()

radius_mean  texture_mean  smoothness_mean  compactness_mean  \
count   569.000000    569.000000       569.000000        569.000000   
mean     14.127292     19.289649         0.096360          0.104341   
std       3.524049      4.301036         0.014064          0.052813   
min       6.981000      9.710000         0.052630          0.019380   
25%      11.700000     16.170000         0.086370          0.064920   
50%      13.370000     18.840000         0.095870          0.092630   
75%      15.780000     21.800000         0.105300          0.130400   
max      28.110000     39.280000         0.163400          0.345400   

       symmetry_mean  fractal_dimension_mean   radius_se  texture_se  \
count     569.000000              569.000000  569.000000  569.000000   
mean        0.181162                0.062798    0.405172    1.216853   
std         0.027414                0.007060    0.277313    0.551648   
min         0.106000                0.049960    0.111500    0.360200   
25%         0.161900                0.057700    0.232400    0.833900   
50%         0.179200                0.061540    0.324200    1.108000   
75%         0.195700                0.066120    0.478900    1.474000   
max         0.304000                0.097440    2.873000    4.885000   

       smoothness_se  compactness_se  concave points_se  symmetry_se  \
count     569.000000      569.000000         569.000000   569.000000   
mean        0.007041        0.025478           0.011796     0.020542   
std         0.003003        0.017908           0.006170     0.008266   
min         0.001713        0.002252           0.000000     0.007882   
25%         0.005169        0.013080           0.007638     0.015160   
50%         0.006380        0.020450           0.010930     0.018730   
75%         0.008146        0.032450           0.014710     0.023480   
max         0.031130        0.135400           0.052790     0.078950   

       symmetry_worst  fractal_dimension_worst  
count      569.000000               569.000000  
mean         0.290076                 0.083946  
std          0.061867                 0.018061  
min          0.156500                 0.055040  
25%          0.250400                 0.071460  
50%          0.282200                 0.080040  
75%          0.317900                 0.092080  
max          0.663800                 0.207500

In [ ]:
data.head()

diagnosis  radius_mean  texture_mean  smoothness_mean  compactness_mean  \
0         M        17.99         10.38          0.11840           0.27760   
1         M        20.57         17.77          0.08474           0.07864   
2         M        19.69         21.25          0.10960           0.15990   
3         M        11.42         20.38          0.14250           0.28390   
4         M        20.29         14.34          0.10030           0.13280   

   symmetry_mean  fractal_dimension_mean  radius_se  texture_se  \
0         0.2419                 0.07871     1.0950      0.9053   
1         0.1812                 0.05667     0.5435      0.7339   
2         0.2069                 0.05999     0.7456      0.7869   
3         0.2597                 0.09744     0.4956      1.1560   
4         0.1809                 0.05883     0.7572      0.7813   

   smoothness_se  compactness_se  concave points_se  symmetry_se  \
0       0.006399         0.04904            0.01587      0.03003   
1       0.005225         0.01308            0.01340      0.01389   
2       0.006150         0.04006            0.02058      0.02250   
3       0.009110         0.07458            0.01867      0.05963   
4       0.011490         0.02461            0.01885      0.01756   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678

In [ ]:
#divide data into features and targets
x = data.iloc[:,1:]
y = data.iloc[:,0]

In [ ]:
#normalization/scaling
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = ss.fit_transform(x)
pd.DataFrame(x).describe()

0             1             2             3             4   \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean  -1.373633e-16  6.868164e-17 -8.366672e-16  1.873136e-16  1.748260e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -2.029648e+00 -2.229249e+00 -3.112085e+00 -1.610136e+00 -2.744117e+00   
25%   -6.893853e-01 -7.259631e-01 -7.109628e-01 -7.470860e-01 -7.032397e-01   
50%   -2.150816e-01 -1.046362e-01 -3.489108e-02 -2.219405e-01 -7.162650e-02   
75%    4.693926e-01  5.841756e-01  6.361990e-01  4.938569e-01  5.307792e-01   
max    3.971288e+00  4.651889e+00  4.770911e+00  4.568425e+00  4.484751e+00   

                 5             6             7             8             9   \
count  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02  5.690000e+02   
mean   4.745277e-16  2.372638e-16 -1.123881e-16 -1.529727e-16  1.748260e-16   
std    1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00  1.000880e+00   
min   -1.819865e+00 -1.059924e+00 -1.554264e+00 -1.776065e+00 -1.298098e+00   
25%   -7.226392e-01 -6.235706e-01 -6.948092e-01 -6.240183e-01 -6.929263e-01   
50%   -1.782793e-01 -2.922452e-01 -1.974976e-01 -2.203352e-01 -2.810204e-01   
75%    4.709834e-01  2.660996e-01  4.665523e-01  3.683553e-01  3.896541e-01   
max    4.910919e+00  8.906909e+00  6.655279e+00  8.029999e+00  6.143482e+00   

               10            11            12            13  
count  569.000000  5.690000e+02  5.690000e+02  5.690000e+02  
mean     0.000000  8.741299e-17  2.622390e-16 -5.744282e-16  
std      1.000880  1.000880e+00  1.000880e+00  1.000880e+00  
min     -1.913447 -1.532890e+00 -2.160960e+00 -1.601839e+00  
25%     -0.674490 -6.516807e-01 -6.418637e-01 -6.919118e-01  
50%     -0.140496 -2.194304e-01 -1.274095e-01 -2.164441e-01  
75%      0.472657  3.556925e-01  4.501382e-01  4.507624e-01  
max      6.649601  7.071917e+00  6.046041e+00  6.846856e+00

In [ ]:
## split data into train and test
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.80,random_state=1)

In [ ]:
xtest

array([[-0.20656118,  0.28631105,  1.01337588, ..., -0.42284231,
         1.10695714,  1.49368807],
       [-0.26052388,  1.3870138 , -0.601368  , ..., -0.85630335,
        -0.73893053, -0.89030039],
       [-0.03047238, -0.84464357, -1.18848289, ..., -1.06940152,
        -1.23720696, -0.93352473],
       ...,
       [ 1.71905507,  0.05825847,  1.20552258, ...,  0.48040333,
         0.21232446, -0.17709882],
       [ 1.18794852,  0.30027345,  0.7429472 , ..., -0.59961692,
         0.28027125, -0.29458036],
       [ 0.2592221 , -0.59332032,  0.17575863, ..., -1.20985258,
        -1.17087796,  0.08557215]])

In [ ]:
y.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [ ]:
ytrain.value_counts()

B    285
M    170
Name: diagnosis, dtype: int64

In [ ]:
x.shape

(569, 14)

In [ ]:
## Build the model
model=tf.models.Sequential() ## an empty model
## add the layers
#no of features = no of neurons
model.add(tf.layers.Dense(16,input_dim=14,activation="relu"))  #input and one hidden layer
model.add(tf.layers.Dense(32,activation='relu'))   #2nd hidden layer
model.add(tf.layers.Dense(1,activation="sigmoid"))  #output layer
#if you take 1 as first parameter then it will give single output (either B or M) if 2 then it will give probability.
model.compile(loss="binary_crossentropy",optimizer='adam', metrics=["accuracy"])
# binary_crossentropy , sparse_categorical_crossentropy

In [ ]:
#label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ytrain=le.fit_transform(ytrain)
ytest= le.fit_transform(ytest)

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [ ]:
## Train the model
model.fit(xtrain,ytrain,epochs=500) #total for testing were 455 and 16 were given by us so 455/16=14.21 == 15

Epoch 1/500
15/15 [==============================] - 1s 2ms/step - loss: 0.6418 - accuracy: 0.6022
Epoch 2/500
15/15 [==============================] - 0s 2ms/step - loss: 0.5483 - accuracy: 0.7297
Epoch 3/500
15/15 [==============================] - 0s 2ms/step - loss: 0.4837 - accuracy: 0.7934
Epoch 4/500
15/15 [==============================] - 0s 2ms/step - loss: 0.4312 - accuracy: 0.8527
Epoch 5/500
15/15 [==============================] - 0s 2ms/step - loss: 0.3813 - accuracy: 0.8747
Epoch 6/500
15/15 [==============================] - 0s 2ms/step - loss: 0.3347 - accuracy: 0.8923
Epoch 7/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2927 - accuracy: 0.9011
Epoch 8/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2559 - accuracy: 0.9165
Epoch 9/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2265 - accuracy: 0.9275
Epoch 10/500
15/15 [==============================] - 0s 2ms/step - loss: 0.2022 - accuracy: 0.9451
Epoch 11/

In [ ]:
## Testing (Evaluation of model/ Prediction)
ypred= model.predict(xtest)
ypred =ypred.round()
ypred

4/4 [==============================] - 0s 3ms/step


array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],

In [ ]:
ytest

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0])

In [ ]:
model.evaluate(xtest,ytest)

4/4 [==============================] - 0s 4ms/step - loss: 0.3873 - accuracy: 0.9561


[0.3872511386871338, 0.9561403393745422]

In [ ]:
#Overfitting and Underfitting
## training accuracy <<< testing accuracy (overfitting otherwise underfitting)


In [ ]:
#testing new data
model.predict([[1,2,3,4,5,6,7,8,9,0,1,2,3,4]])

1/1 [==============================] - 0s 81ms/step


array([[1.]], dtype=float32)

1/1 [==============================] - 0s 36ms/step


array([[1.]], dtype=float32)

In [ ]:
# Save the model - for future use
model.save("cancer.h5")

In [ ]:
mymodel= tf.models.load_model("/content/cancer.h5")
mymodel.predict([[1,2,3,4,5,6,7,8,9,0,1,2,3,4]])

1/1 [==============================] - 0s 96ms/step


array([[1.]], dtype=float32)

In [ ]:
## Confusion Matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(ytest,ypred)
cm

array([[72,  0],
       [ 5, 37]])

In [ ]:
cm.diagonal()

array([72, 37])

In [ ]:
accuracy=cm.diagonal().sum() / cm.sum()
accuracy

0.956140350877193

In [ ]:
#OR
from sklearn.metrics import accuracy_score
a= accuracy_score(ytest,ypred)
a

0.956140350877193